add terra extension
alleslabs/cosmos-kit pull request #3
Opened 2023-04-22 10:03 UTC by evilpeach

2023-04-24 21:16 UTC, pyramation commented on packages/example/config/terra2testnet.ts
> +export const terra2testnet: Chain = {
will merge this all for now, however, let's move this to the chain-registry soon

2023-04-24 21:16 UTC, pyramation commented on packages/example/pages/_app.tsx
> +          assetLists={[...assets, terra2testnetAssets]}
will merge this all for now, however, let's move this to the chain-registry soon

2023-04-25 12:05 UTC, alecande11 requested changes

2023-04-25 12:05 UTC, alecande11 commented on wallets/terra-extension/src/extension/client.ts
> +      address: account.address,
This should be `account.addresses[chainID]`

2023-11-11 23:24 UTC, closed without merging